FROM node:20-bookworm-slim
WORKDIR /app
COPY russian-trusted-root-ca.pem /app/russian-trusted-root-ca.pem
ENV NODE_EXTRA_CA_CERTS=/app/russian-trusted-root-ca.pem
ENV BOT_IMAGE_REVISION=v77-mailru-inventory-20260829-1
COPY package-final.json ./package.json
RUN npm install --omit=dev
COPY bot-giga-v14.js ./bot-giga-v14.js
COPY patch-v14-fullchat.mjs ./patch-v14-fullchat.mjs
COPY patch-v14-silent.mjs ./patch-v14-silent.mjs
COPY patch-v14-webhook.mjs ./patch-v14-webhook.mjs
COPY patch-v14-block-stale.mjs ./patch-v14-block-stale.mjs
COPY patch-v14-max-history.mjs ./patch-v14-max-history.mjs
COPY patch-v14-freshscope.mjs ./patch-v14-freshscope.mjs
COPY patch-v14-dialog-routing.mjs ./patch-v14-dialog-routing.mjs
COPY patch-v14-private-owner.mjs ./patch-v14-private-owner.mjs
COPY patch-v14-accounting-accuracy.mjs ./patch-v14-accounting-accuracy.mjs
COPY patch-v14-release-series.mjs ./patch-v14-release-series.mjs
COPY patch-v14-text-release-logic.mjs ./patch-v14-text-release-logic.mjs
COPY patch-v14-openai-brain.mjs ./patch-v14-openai-brain.mjs
COPY patch-v14-semantic-thread.mjs ./patch-v14-semantic-thread.mjs
COPY patch-v56-ledger-compat.mjs ./patch-v56-ledger-compat.mjs
COPY patch-v14-persistent-ledger-v2.mjs ./patch-v14-persistent-ledger-v2.mjs
COPY patch-v56-ledger-safety.mjs ./patch-v56-ledger-safety.mjs
COPY patch-v57-ledger-backfill-gate.mjs ./patch-v57-ledger-backfill-gate.mjs
COPY patch-v58-openai-quota-fallback.mjs ./patch-v58-openai-quota-fallback.mjs
COPY patch-v59-resumable-ledger.mjs ./patch-v59-resumable-ledger.mjs
COPY patch-v60-monotonic-backfill.mjs ./patch-v60-monotonic-backfill.mjs
COPY patch-v61-date-dedup.mjs ./patch-v61-date-dedup.mjs
COPY patch-v62-history-export.mjs ./patch-v62-history-export.mjs
COPY patch-v63-safe-ledger-export-link.mjs ./patch-v63-safe-ledger-export-link.mjs
COPY patch-v64-media-export-command.mjs ./patch-v64-media-export-command.mjs
COPY patch-v65-media-container-export.mjs ./patch-v65-media-container-export.mjs
COPY patch-v65-server-anchor-fix.mjs ./patch-v65-server-anchor-fix.mjs
COPY patch-v68-streaming-media-export.mjs ./patch-v68-streaming-media-export.mjs
COPY patch-v69-date-range-media-export.mjs ./patch-v69-date-range-media-export.mjs
COPY patch-v71-reliable-webhook.mjs ./patch-v71-reliable-webhook.mjs
COPY patch-v72-multichat-export-command.mjs ./patch-v72-multichat-export-command.mjs
COPY patch-v74-private-forward-import.mjs ./patch-v74-private-forward-import.mjs
COPY patch-v75-private-import-screenshots.mjs ./patch-v75-private-import-screenshots.mjs
COPY patch-v76-forward-source-chat-register.mjs ./patch-v76-forward-source-chat-register.mjs
COPY patch-v77-mailru-inventory.mjs ./patch-v77-mailru-inventory.mjs
RUN node patch-v14-fullchat.mjs
RUN node patch-v14-silent.mjs
RUN node patch-v14-webhook.mjs
RUN node patch-v14-block-stale.mjs
RUN node patch-v14-max-history.mjs
RUN node patch-v14-freshscope.mjs
RUN node patch-v14-dialog-routing.mjs
RUN node patch-v14-private-owner.mjs
RUN node patch-v14-accounting-accuracy.mjs
RUN node patch-v14-release-series.mjs
RUN node patch-v14-text-release-logic.mjs
RUN node patch-v14-openai-brain.mjs
RUN node patch-v14-semantic-thread.mjs
RUN node patch-v56-ledger-compat.mjs
RUN node patch-v14-persistent-ledger-v2.mjs
RUN node patch-v56-ledger-safety.mjs
RUN node patch-v57-ledger-backfill-gate.mjs
RUN node patch-v58-openai-quota-fallback.mjs
RUN node patch-v59-resumable-ledger.mjs
RUN node patch-v60-monotonic-backfill.mjs
RUN node patch-v61-date-dedup.mjs
RUN node patch-v62-history-export.mjs
RUN node patch-v63-safe-ledger-export-link.mjs
RUN node patch-v64-media-export-command.mjs
RUN node patch-v65-server-anchor-fix.mjs
RUN node patch-v65-media-container-export.mjs
RUN node patch-v68-streaming-media-export.mjs
RUN node patch-v69-date-range-media-export.mjs
RUN node patch-v71-reliable-webhook.mjs
RUN node patch-v72-multichat-export-command.mjs
RUN node patch-v74-private-forward-import.mjs
RUN node patch-v75-private-import-screenshots.mjs
RUN node patch-v76-forward-source-chat-register.mjs
RUN node patch-v77-mailru-inventory.mjs
RUN node --check bot.js
EXPOSE 3000
CMD ["node", "bot.js"]