name: Build current MAX bot

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-current.yml'

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build MAX bot container
        run: docker build --progress=plain -t max-uchet-bot-gaina:test .
